# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulator.proto',
  package='simulation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsimulator.proto\x12\nsimulation\"1\n\x0bInitRequest\x12\x11\n\tStartDate\x18\x01 \x01(\t\x12\x0f\n\x07\x45ndDate\x18\x02 \x01(\t\"\x8d\x01\n\x0bStepRequest\x12\x10\n\x08numSteps\x18\x01 \x01(\x05\x12:\n\ncell_state\x18\x02 \x03(\x0b\x32&.simulation.StepRequest.CellStateEntry\x1a\x30\n\x0e\x43\x65llStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x93\x01\n\rStateResponse\x12\x13\n\x0b\x63urrentStep\x18\x01 \x01(\x05\x12;\n\temissions\x18\x02 \x03(\x0b\x32(.simulation.StateResponse.EmissionsEntry\x1a\x30\n\x0e\x45missionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x8f\x01\n\tSimulator\x12\x46\n\x10start_simulation\x12\x17.simulation.InitRequest\x1a\x19.simulation.StateResponse\x12:\n\x04step\x12\x17.simulation.StepRequest\x1a\x19.simulation.StateResponseb\x06proto3'
)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='simulation.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='StartDate', full_name='simulation.InitRequest.StartDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EndDate', full_name='simulation.InitRequest.EndDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=80,
)


_STEPREQUEST_CELLSTATEENTRY = _descriptor.Descriptor(
  name='CellStateEntry',
  full_name='simulation.StepRequest.CellStateEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='simulation.StepRequest.CellStateEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='simulation.StepRequest.CellStateEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=224,
)

_STEPREQUEST = _descriptor.Descriptor(
  name='StepRequest',
  full_name='simulation.StepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numSteps', full_name='simulation.StepRequest.numSteps', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_state', full_name='simulation.StepRequest.cell_state', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STEPREQUEST_CELLSTATEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=224,
)


_STATERESPONSE_EMISSIONSENTRY = _descriptor.Descriptor(
  name='EmissionsEntry',
  full_name='simulation.StateResponse.EmissionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='simulation.StateResponse.EmissionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='simulation.StateResponse.EmissionsEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=374,
)

_STATERESPONSE = _descriptor.Descriptor(
  name='StateResponse',
  full_name='simulation.StateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentStep', full_name='simulation.StateResponse.currentStep', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emissions', full_name='simulation.StateResponse.emissions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATERESPONSE_EMISSIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=374,
)

_STEPREQUEST_CELLSTATEENTRY.containing_type = _STEPREQUEST
_STEPREQUEST.fields_by_name['cell_state'].message_type = _STEPREQUEST_CELLSTATEENTRY
_STATERESPONSE_EMISSIONSENTRY.containing_type = _STATERESPONSE
_STATERESPONSE.fields_by_name['emissions'].message_type = _STATERESPONSE_EMISSIONSENTRY
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['StepRequest'] = _STEPREQUEST
DESCRIPTOR.message_types_by_name['StateResponse'] = _STATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulation.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

StepRequest = _reflection.GeneratedProtocolMessageType('StepRequest', (_message.Message,), {

  'CellStateEntry' : _reflection.GeneratedProtocolMessageType('CellStateEntry', (_message.Message,), {
    'DESCRIPTOR' : _STEPREQUEST_CELLSTATEENTRY,
    '__module__' : 'simulator_pb2'
    # @@protoc_insertion_point(class_scope:simulation.StepRequest.CellStateEntry)
    })
  ,
  'DESCRIPTOR' : _STEPREQUEST,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulation.StepRequest)
  })
_sym_db.RegisterMessage(StepRequest)
_sym_db.RegisterMessage(StepRequest.CellStateEntry)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {

  'EmissionsEntry' : _reflection.GeneratedProtocolMessageType('EmissionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATERESPONSE_EMISSIONSENTRY,
    '__module__' : 'simulator_pb2'
    # @@protoc_insertion_point(class_scope:simulation.StateResponse.EmissionsEntry)
    })
  ,
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulation.StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)
_sym_db.RegisterMessage(StateResponse.EmissionsEntry)


_STEPREQUEST_CELLSTATEENTRY._options = None
_STATERESPONSE_EMISSIONSENTRY._options = None

_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='simulation.Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=377,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='start_simulation',
    full_name='simulation.Simulator.start_simulation',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='step',
    full_name='simulation.Simulator.step',
    index=1,
    containing_service=None,
    input_type=_STEPREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
