# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_action = channel.unary_unary(
                '/agent.Agent/get_action',
                request_serializer=agent__pb2.StateResponse.SerializeToString,
                response_deserializer=agent__pb2.StepRequest.FromString,
                )


class AgentServicer(object):
    """Define the service
    """

    def get_action(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_action': grpc.unary_unary_rpc_method_handler(
                    servicer.get_action,
                    request_deserializer=agent__pb2.StateResponse.FromString,
                    response_serializer=agent__pb2.StepRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Define the service
    """

    @staticmethod
    def get_action(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.Agent/get_action',
            agent__pb2.StateResponse.SerializeToString,
            agent__pb2.StepRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
